spring:
   datasource:
    url: jdbc:mysql://127.0.0.1:3306/gamestore
    username: root  
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2    
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
eureka:
   client:
     service-url:      
      defaultZone: http://localhost:8761/eureka

